name: waf-rule-mcp preview

on:
  pull_request:
      branches:
        - main

env:
  GEN0SEC_MCP_SERVER_REGISTRY_IMAGE: ghcr.io/gen0sec/mcp-server/gen0sec-mcp-server

jobs:
  gen0sec-mcp-server-prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.platforms.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create matrix
        id: platforms
        run: |
          echo "matrix=[\"linux/amd64\",\"linux/arm64\"]" >>${GITHUB_OUTPUT}

      - name: Show matrix
        run: |
          echo ${{ steps.platforms.outputs.matrix }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GEN0SEC_MCP_SERVER_REGISTRY_IMAGE }}
          tags: |
            type=sha,format=short
            type=match,pattern=v(\d+\.\d+\.\d+),group=1
            type=match,pattern=v(\d+\.\d+),group=1
            type=match,pattern=v(\d+),group=1
            type=raw,value=latest

      - name: Rename meta bake definition file
        run: |
          mv "${{ steps.meta.outputs.bake-file }}" "${{ runner.temp }}/gen0sec-mcp-server-bake-meta.json"

      - name: Upload meta bake definition
        uses: actions/upload-artifact@v6
        with:
          name: gen0sec-mcp-server-bake-meta
          path: ${{ runner.temp }}/gen0sec-mcp-server-bake-meta.json
          if-no-files-found: error
          retention-days: 1

  gen0sec-mcp-server-build:
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    needs:
      - gen0sec-mcp-server-prepare
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.gen0sec-mcp-server-prepare.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Download meta bake definition
        uses: actions/download-artifact@v6
        with:
          name: gen0sec-mcp-server-bake-meta
          path: ${{ runner.temp }}

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        id: bake
        uses: docker/bake-action@v6
        with:
          files: |
            docker-bake.hcl
            cwd://${{ runner.temp }}/gen0sec-mcp-server-bake-meta.json
          targets: image
          set: |
            *.tags=${{ env.GEN0SEC_MCP_SERVER_REGISTRY_IMAGE }}
            *.platform=${{ matrix.platform }}
            *.output=type=image,push-by-digest=true,name-canonical=true,push=true
